export const kategoriak = [
    {
      angol: "Echoes of the future",
      magyar: "A jövő visszhangjai",
      magyarLeir: "Ez így gurjál meg az artáson, ez volt az érterhevet...",
      angolLeir: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    },
    {
      angol: "Paths of the unknown",
      magyar: "Az ismeretlen ösvényei",
      magyarLeir: "Ez így gurjál meg az artáson, ez volt az érterhevet...",
      angolLeir: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    },
    {
      angol: "Nomad legacy",
      magyar: "Nomád örökség",
      magyarLeir: "Ez így gurjál meg az artáson, ez volt az érterhevet...",
      angolLeir: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    },
    {
      angol: "Urban chronicles",
      magyar: "Városi krónikák",
      magyarLeir: "Ez így gurjál meg az artáson, ez volt az érterhevet...",
      angolLeir: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    },
    {
      angol: "Post-apocalyptic futurism",
      magyar: "Poszt-apokaliptikus futurizmus",
      magyarLeir: "Ez így gurjál meg az artáson, ez volt az érterhevet...",
      angolLeir: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    },
    {
      angol: "Urban survival",
      magyar: "Városi túlélés",
      magyarLeir: "Ez így gurjál meg az artáson, ez volt az érterhevet...",
      angolLeir: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    },
    {
      angol: "Adaptive fashion",
      magyar: "Adaptív divat",
      magyarLeir: "Ez így gurjál meg az artáson, ez volt az érterhevet...",
      angolLeir: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    },
    {
      angol: "Rebirth and renewal",
      magyar: "Újjászületés és megújulás",
      magyarLeir: "Ez így gurjál meg az artáson, ez volt az érterhevet...",
      angolLeir: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    },
    {
      angol: "Survival through unity",
      magyar: "Túlélés az egységen keresztül",
      magyarLeir: "Ez így gurjál meg az artáson, ez volt az érterhevet...",
      angolLeir: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    },
    {
      angol: "Minimalism and adaptation",
      magyar: "Minimalizmus és alkalmazkodás",
      magyarLeir: "Ez így gurjál meg az artáson, ez volt az érterhevet...",
      angolLeir: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    },
    {
      angol: "Warrior spirit",
      magyar: "Harcos szellem",
      magyarLeir: "Ez így gurjál meg az artáson, ez volt az érterhevet...",
      angolLeir: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    },
    {
      angol: "Celebrating the strength in diversity",
      magyar: "A sokféleségben rejlő erő ünneplése",
      magyarLeir: "Ez így gurjál meg az artáson, ez volt az érterhevet...",
      angolLeir: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    },
    {
      angol: "Cyber survival",
      magyar: "Kibernetikus túlélés",
      magyarLeir: "Ez így gurjál meg az artáson, ez volt az érterhevet...",
      angolLeir: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    },
    {
      angol: "Nomad alchemy",
      magyar: "Nomád alkímia",
      magyarLeir: "Ez így gurjál meg az artáson, ez volt az érterhevet...",
      angolLeir: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    },
    {
      angol: "Uncharted terrain",
      magyar: "Feltérképezetlen terep",
      magyarLeir: "Ez így gurjál meg az artáson, ez volt az érterhevet...",
      angolLeir: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    },
    {
      angol: "Crafting the unknown",
      magyar: "Az ismeretlen megformálása",
      magyarLeir: "Ez így gurjál meg az artáson, ez volt az érterhevet...",
      angolLeir: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    },
    {
      angol: "Survival strategies decoded",
      magyar: "Túlélési stratégiák dekódolva/megfejtve",
      magyarLeir: "Ez így gurjál meg az artáson, ez volt az érterhevet...",
      angolLeir: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    },
    {
      angol: "Beyond tomorrow",
      magyar: "A holnapon túl",
      magyarLeir: "Ez így gurjál meg az artáson, ez volt az érterhevet...",
      angolLeir: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    },
    {
      angol: "Navigating to the unknow",
      magyar: "Navigálás az ismeretlen felé",
      magyarLeir: "Ez így gurjál meg az artáson, ez volt az érterhevet...",
      angolLeir: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    },
    {
      angol: "Escape from dystopia",
      magyar: "Menekülés a disztópiából",
      magyarLeir: "Ez így gurjál meg az artáson, ez volt az érterhevet...",
      angolLeir: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    },
    {
      angol: "Survival strategies: the art of mimicry",
      magyar: "Túlélési stratégiák: a mimikri művészete",
      magyarLeir: "Ez így gurjál meg az artáson, ez volt az érterhevet...",
      angolLeir: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    },
  ];